language: node_js

node_js:
  - "14"

addons:
  sonarcloud:
    organization: "maju6406"
    token:
      secure: "e0a63642bb7ddbf4d273ccb5c5a798408b95783d"
      
install:
  - npm install

script:
  - npm run test && npm run tslint && sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
